# This is a basic workflow to help you get started with Actions

name: Open Chrome Pop-up

# Controls when the workflow will run
on:
 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          start chrome "https://google.com"
